In [14]:
import numpy as np

In [15]:
a = np.array([12,21,6,78,76,34,23,56,89,22,45,56])
a.dtype

dtype('int32')

In [3]:
a.itemsize
#gives the value of bites

4

In [4]:
a.size

12

In [8]:
a.reshape(3,4)
a.reshape(2,3,2)

array([[[12, 21],
        [ 6, 78],
        [76, 34]],

       [[23, 56],
        [89, 22],
        [45, 56]]])

In [9]:
a.ndim #dimention array

1

In [13]:
b = np.array([[12, 21, 6, 78, 76], [34, 23, 56, 89, 22]])
b.ndim

2

In [19]:
c = a.copy()
a[0]= 10
c


array([10, 21,  6, 78, 76, 34, 23, 56, 89, 22, 45, 56])

In [20]:
a =np.zeros(2)
a
# makes array of zeros

array([0., 0.])

In [22]:
b = np.ones(5)
b
#codeshare

array([1., 1., 1., 1., 1.])